

// FIX: Explicitly type GAS_URL as a string to prevent TypeScript from inferring a narrow literal type, which was causing comparison errors.
export const GAS_URL: string = 'https://script.google.com/macros/s/AKfycbzpdXIKXqUsK5pcdVzdRQ6YEXOjTlB3hFC5El_PqLwNKRR79tJb_-lTIqA0z95yxRSzug/exec';
export const GOOGLE_DRIVE_FOLDER_ID: string = '1YOccTHgmK8R4QAW89PLtcvMFb8DAMu7t';

export const PREDEFINED_STUDENT_PICTURES = [
    '/student-avatars/01.png',
    '/student-avatars/02.png',
    '/student-avatars/03.png',
    '/student-avatars/04.png',
    '/student-avatars/05.png',
    '/student-avatars/06.png',
    '/student-avatars/07.png',
    '/student-avatars/08.png',
    '/student-avatars/09.png',
    '/student-avatars/10.png',
    '/student-avatars/11.png',
    '/student-avatars/12.png',
];

export const translations = {
    en: {
        appName: "iPad Check",
        login: "Login",
        email: "Email",
        password: "Password",
        home: "Home",
        services: "Services",
        history: "History",
        profile: "Profile",
        logout: "Logout",
        language: "Language",
        searchDevice: "Search Device...",
        available: "Available",
        borrowed: "Borrowed",
        maintenance: "Maintenance",
        pending: "Pending",
        lost: "Lost",
        allDevices: "All Devices",
        myDevices: "My Devices",
        borrow: "Borrow",
        return: "Return",
        reportIssue: "Report Issue",
        borrowRequestSuccess: "Borrow request submitted successfully!",
        returnSuccess: "Device returned successfully!",
        repairRequestSuccess: "Repair request submitted successfully!",
        errorInvalidCredentials: "Invalid username or password.",
        deviceNotFound: "Device not found.",
        confirmDeleteDevice: "Are you sure you want to delete this item?",
        addSuccess: "Successfully added",
        editSuccess: "Successfully edited",
        notSpecified: "Not Specified",
        errorInvalidFileType: "Invalid file type. Please upload an image.",
        errorFileSizeTooLarge: "File size is too large. Maximum is {maxSize}MB.",
        approvals: "Approvals",
        approve: "Approve",
        reject: "Reject",
        approveSuccess: "Approved successfully:",
        rejectSuccess: "Rejected successfully:",
        userManagement: "User Management",
        reports: "Reports",
        productManagement: "Product Management",
        assignUser: "Assign User",
        addDevice: "Add Device",
        teacher: "Teacher",
        student: "Student",
    },
    th: {
        appName: "iPad Check",
        login: "เข้าสู่ระบบ",
        email: "อีเมล",
        password: "รหัสผ่าน",
        home: "หน้าแรก",
        services: "แจ้งซ่อม",
        history: "ประวัติ",
        profile: "โปรไฟล์",
        logout: "ออกจากระบบ",
        language: "ภาษา",
        searchDevice: "ค้นหาอุปกรณ์...",
        available: "ว่าง",
        borrowed: "ถูกยืม",
        maintenance: "ซ่อมบำรุง",
        pending: "รออนุมัติ",
        lost: "สูญหาย",
        allDevices: "อุปกรณ์ทั้งหมด",
        myDevices: "อุปกรณ์ของฉัน",
        borrow: "ยืม",
        return: "คืน",
        reportIssue: "แจ้งปัญหา",
        borrowRequestSuccess: "ส่งคำขอยืมอุปกรณ์สำเร็จ!",
        returnSuccess: "คืนอุปกรณ์สำเร็จ!",
        repairRequestSuccess: "ส่งใบแจ้งซ่อมสำเร็จ!",
        errorInvalidCredentials: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
        deviceNotFound: "ไม่พบอุปกรณ์นี้",
        confirmDeleteDevice: "คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้?",
        addSuccess: "เพิ่มข้อมูลสำเร็จ",
        editSuccess: "แก้ไขข้อมูลสำเร็จ",
        notSpecified: "ไม่ระบุ",
        errorInvalidFileType: "ไฟล์ไม่ถูกต้อง กรุณาอัปโหลดไฟล์รูปภาพ",
        errorFileSizeTooLarge: "ไฟล์มีขนาดใหญ่เกินไป ขนาดสูงสุดคือ {maxSize}MB",
        approvals: "รายการอนุมัติ",
        approve: "อนุมัติ",
        reject: "ปฏิเสธ",
        approveSuccess: "อนุมัติสำเร็จ:",
        rejectSuccess: "ปฏิเสธสำเร็จ:",
        userManagement: "จัดการผู้ใช้",
        reports: "รายงาน",
        productManagement: "จัดการผลิตภัณฑ์",
        assignUser: "กำหนดผู้ใช้",
        addDevice: "เพิ่มอุปกรณ์",
        teacher: "ครู",
        student: "นักเรียน",
    }
};